# Generated by Django 5.1.7 on 2025-03-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
